name: ecommerce_no_shoppu
description: "A new Flutter project."


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.0


#-------------- Packages ----------------#

dependencies:
  flutter:
    sdk: flutter

# Utility Packages
  http: ^1.2.2
  url_launcher: ^6.3.1
  intl: ^0.19.0
  logger: ^2.4.0
  lottie: ^3.1.3
  connectivity_plus: ^6.1.0
  flutter_native_splash: ^2.4.2
  smooth_page_indicator: ^1.2.0+3





# Icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8
  google_fonts: ^6.2.1
 


# State Management
  get: ^4.6.6
  get_storage: ^2.1.1


# Firebase
  firebase_core: ^3.8.0
  firebase_storage: ^12.3.4
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  google_sign_in: ^6.2.2



# Product Specific
  carousel_slider: ^5.0.0
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1






#-------------- Packages End ----------------#


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0




flutter:

  uses-material-design: true


  #-------------- Local Assets ----------------#


  assets:
   - assets/logos/
   - assets/icons/categories/
   - assets/icons/brands/
   - assets/images/on_boardingu_no_imeigi/
   - assets/images/animations/
   - assets/images/banners/
   - assets/images/products/
   - assets/images/user/
   - assets/images/reviews/
   - assets/icons/payment_methods/







  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
